name: welcome_pages
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - images/Security On-amico.png
   - images/Chat bot-amico.png
   - images/Cyber attack-amico.png
   - images/Login-bro (1).png
   - images/Mobile login-bro.png
   - images/Sign in-amico (1).png
  fonts:
    - family: Fondamento
      fonts:
        - asset: fonts/Fondamento-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
